name: Daily Tech Trends Monitor

on:
  schedule:
    - cron: '0 5 * * *'  # 8AM Uganda/Kenya time
  workflow_dispatch:

jobs:
  send-tech-trends:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml

    - name: Download sent trends log (if exists)
      uses: actions/download-artifact@v4
      with:
        name: sent-trends-log
        path: .

    - name: Run tech trends monitor
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      run: |
        python tech_trends_monitor.py

    - name: Upload updated sent log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sent-trends-log
        path: sent_trends_log.json
        retention-days: 7

    - name: Upload log file
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tech-trends-log
        path: tech_trends.log
        retention-days: 7
